// Central Schedule C (and Schedule 1 above-the-line) mapping for UI categories.
// Used by tax treatment helpers and export generators.

export const SCHEDULE_C_LINES: Record<string, { line: string; label: string; deductPct?: number }> = {
  // --- INCOME ---
  "Sales Revenue": { line: "1", label: "Gross receipts or sales" },
  "Freelance Income": { line: "1", label: "Gross receipts or sales" },
  "Returns & Allowances": { line: "2", label: "Returns and allowances" },
  "Refunds Given": { line: "2", label: "Returns and allowances" },
  "Interest Income": { line: "6", label: "Other income (interest)" },
  "Other Income": { line: "6", label: "Other income" },
  // --- COGS (Line 4) ---
  "Cost of Service": { line: "4", label: "Cost of goods sold" },

  // --- EXPENSES ---
  "Advertising & Marketing": { line: "8", label: "Advertising" },
  "Soccer Team Sponsorship": { line: "8", label: "Advertising" },
  "Social Media & Online Presence": { line: "8", label: "Advertising" },
  "Gas & Auto Expense": { line: "9", label: "Car and truck expenses" },
  "Parking Expense": { line: "9", label: "Car and truck expenses" },
  "Merchant Processing Fees": { line: "10", label: "Commissions and fees" },
  "Merchant Fees Expense": { line: "10", label: "Commissions and fees" },
  "Contract Labor": { line: "11", label: "Contract labor" },
  "Equipment & Depreciation": { line: "13", label: "Depreciation and section 179" },
  "Computer Equipment Expense": { line: "13", label: "Depreciation and section 179" },
  "Insurance Expense - Business": { line: "15", label: "Insurance (other than health)" },
  "Insurance Expense - Auto": { line: "15", label: "Insurance (auto)" },
  "Health Insurance": { line: "S1-17", label: "Self-employed health insurance (Schedule 1 Line 17 -- above-the-line)" },
  "Interest Expense": { line: "16b", label: "Interest (other)" },
  "Bank & ATM Fee Expense": { line: "16b", label: "Bank fees / Interest (other)" },
  "Professional Service Expense": { line: "17", label: "Legal and professional services" },
  "Tax Software & Services": { line: "17", label: "Legal and professional services" },
  "Office Supplies": { line: "18", label: "Office expense" },
  "Office Supply Expense": { line: "18", label: "Office expense" },
  "Office Kitchen Supplies": { line: "18", label: "Office expense" },
  "Software & Web Hosting Expense": { line: "27a", label: "Other expenses (software)" },
  "Rent Expense": { line: "20b", label: "Rent (other business property)" },
  "Rent Vehicles & Equipment Expense": { line: "20a", label: "Rent (vehicles/equipment)" },
  "Travel Expense": { line: "24a", label: "Travel" },
  "Business Meals Expense": { line: "24b", label: "Meals (50% deductible)", deductPct: 50 },
  "Phone & Internet Expense": { line: "25", label: "Utilities" },
  "Utilities Expense": { line: "25", label: "Utilities" },
  "Depletion Expense": { line: "12", label: "Depletion" },
  "Employee Benefit Programs Expense": { line: "14", label: "Employee benefit programs" },
  "Mortgage Interest Expense": { line: "16a", label: "Mortgage interest" },
  "Repairs & Maintenance Expense": { line: "21", label: "Repairs and maintenance" },
  "Supplies Expense": { line: "22", label: "Supplies" },
  "Wages Expense": { line: "26", label: "Wages" },
  "License & Fee Expense": { line: "23", label: "Taxes and licenses" },
  "California LLC Fee": { line: "23", label: "Taxes and licenses (CA franchise tax)" },
  "Client Gifts": { line: "27a", label: "Other expenses (gifts $25/person limit)" },
  "Eye Care - Business Expense": { line: "27a", label: "Other expenses (occupational eye care)" },
  "Education & Training": { line: "27a", label: "Other expenses (training)" },
  "Postage & Shipping Expense": { line: "27a", label: "Other expenses (postage)" },
  "Waste & Disposal": { line: "27a", label: "Other expenses (waste)" },
  "Waste & Sanitation Expense": { line: "27a", label: "Other expenses (waste)" },
  "Home Improvement": { line: "27a", label: "Other expenses (home improvements)" },
  "Home Improvement (Business)": { line: "27a", label: "Other expenses (home improvements)" },
  "Home Office Expense": { line: "30", label: "Business use of home" },
  "SEP-IRA Contribution": { line: "S1-16", label: "Self-employed SEP/SIMPLE/qualified plans (Schedule 1)" },

  // --- Capital / financing and explicitly non-expense categories ---
  "Business Treasury Investment": { line: "N/A", label: "Asset -- not current year deduction" },
  "Owner's Contribution": { line: "N/A", label: "Owner contribution — not gross receipts" },
  "Loan Proceeds": { line: "N/A", label: "Loan / capital advance — not gross receipts" },
  "Business Loan Proceeds": { line: "N/A", label: "Loan proceeds -- not income, not deductible (debt)" },
  "Loan Repayment - Principal": { line: "N/A", label: "Loan principal -- not deductible" },
  "Loan Interest Expense": { line: "16b", label: "Interest expense (deductible)" },
  "Crypto Treasury Purchase": { line: "N/A", label: "Capital asset purchase -- not expense (track cost basis)" },

  // --- HAIR STYLIST / SALON PROFESSIONAL ---
  "Service Income": { line: "1", label: "Gross receipts or sales (services)" },
  "Booth Rental Expense": { line: "20b", label: "Rent or lease (other business property)" },
  "Hair Products & Color": { line: "22", label: "Supplies (color, shampoo, treatments)" },
  "Styling Tools & Equipment": { line: "22", label: "Supplies (tools under $2,500) / Line 13 if depreciating" },
  "Disposable Supplies": { line: "22", label: "Supplies (foils, gloves, capes, neck strips)" },
  "Booking & Payment Software": { line: "27a", label: "Other expenses (Vagaro, GlossGenius, StyleSeat, Booksy)" },
  "Laundry & Cleaning": { line: "27a", label: "Other expenses (towel service, cape laundering)" },
  "Cosmetology License & Permits": { line: "23", label: "Taxes and licenses (CA Board renewal, city permit)" },
  "Professional Liability Insurance": { line: "15", label: "Insurance (stylist/salon liability -- not health)" },
  "Retail Product Sales COGS": { line: "4", label: "Cost of goods sold (retail products for resale)" },
}

